HEROKU_URL = "https://the-internet.herokuapp.com"
GOOGLE_URL = "https://www.google.com"
REELLY_SIGNIN_URL = "https://soft.reelly.io/sign-in"
TUTORIALSPOINT_URL = "https://www.tutorialspoint.com/selenium/practice/upload-download.php"


AUTH_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTAxOSIsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJyZWFsX2VzdGF0ZV9hZ2VuY3kiXSwic2NvcGUiOiJsaXN0aW5nczpyZWFkIGxpc3RpbmdzOndyaXRlIHByb2ZpbGUiLCJzZXNzaW9uX2lkIjoiYjRjOWRhYjNlMjliZTkzYWNjNTRiNjViYTZkMTY1MTAiLCJpYXQiOjE3ODgzNzkyNzQsImV4cCI6MTc4ODM4MDE3NCwianRpIjoiYjRjOWRhYjNlMjliZTkzYWNjNTRiNjViYTZkMTY1MTAifQ.uQc9c6ciufrcZV3jx5OwHvyswNqdTjNaC9J61YSIajI"
AUTH_REFRESH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTAxOSIsInR5cGUiOiJyZWZyZXNoIiwic2Vzc2lvbl9pZCI6ImI0YzlkYWIzZTI5YmU5M2FjYzU0YjY1YmE2ZDE2NTEwIiwiaWF0IjoxNzg4Mzc5Mjc0LCJleHAiOjE3OTA5NzEyNzQsImp0aSI6ImI0YzlkYWIzZTI5YmU5M2FjYzU0YjY1YmE2ZDE2NTEwIn0.w4dO1HOLqonylwAuVuJvlPrnNsFpyIxw0iKCelh0x9o"